version: "3.6"

x-service-settings: &service_settings
  env_file: .env
  build: &build_settings
    context: /opt/rapids
    args:
      UID: ${_UID:-1000}
      GID: ${_GID:-1000}
      BUILD_TESTS: "OFF"
      PYTHON_VERSION: "3.7"
      CUDA_VERSION: "${CUDA_VERSION:-10.0}"
      LINUX_VERSION: "${LINUX_VERSION:-ubuntu18.04}"
      RAPIDS_VERSION: "${RAPIDS_VERSION:-latest}"
      RAPIDS_NAMESPACE: "${RAPIDS_NAMESPACE:-anon}"

services:

  01-cuda:
    <<: *service_settings
    image: rapidsai/${RAPIDS_NAMESPACE:-anon}/cuda:${RAPIDS_VERSION:-latest}
    build:
      <<: *build_settings
      dockerfile: /opt/rapids/compose/dockerfiles/base/01-cuda.Dockerfile

  02-rmm:
    <<: *service_settings
    image: rapidsai/${RAPIDS_NAMESPACE:-anon}/rmm:${RAPIDS_VERSION:-latest}
    build:
      <<: *build_settings
      dockerfile: /opt/rapids/compose/dockerfiles/base/02-rmm.Dockerfile

  03-custrings:
    <<: *service_settings
    image: rapidsai/${RAPIDS_NAMESPACE:-anon}/custrings:${RAPIDS_VERSION:-latest}
    build:
      <<: *build_settings
      dockerfile: /opt/rapids/compose/dockerfiles/base/03-custrings.Dockerfile

  04-cudf:
    <<: *service_settings
    image: rapidsai/${RAPIDS_NAMESPACE:-anon}/cudf:${RAPIDS_VERSION:-latest}
    build:
      <<: *build_settings
      dockerfile: /opt/rapids/compose/dockerfiles/base/04-cudf.Dockerfile

  05-cugraph:
    <<: *service_settings
    image: rapidsai/${RAPIDS_NAMESPACE:-anon}/cugraph:${RAPIDS_VERSION:-latest}
    build:
      <<: *build_settings
      dockerfile: /opt/rapids/compose/dockerfiles/base/05-cugraph.Dockerfile
