version: "3.6"

x-service-settings: &service_settings
  env_file: .env
  build: &build_settings
    context: ..
    args:
      UID: ${_UID:-1000}
      GID: ${_GID:-1000}
      BUILD_TESTS: "OFF"
      PYTHON_VERSION: "3.7"
      RAPIDS_HOME: "${RAPIDS_HOME:-$PWD}"
      CUDA_VERSION: "${CUDA_VERSION:-10.0}"
      RAPIDS_VERSION: "${RAPIDS_VERSION:-latest}"
      RAPIDS_NAMESPACE: "${RAPIDS_NAMESPACE:-anon}"
      LINUX_VERSION: "${LINUX_VERSION:-ubuntu18.04}"

services:

  base:
    <<: *service_settings
    image: rapidsai/${RAPIDS_NAMESPACE:-anon}/base:${RAPIDS_VERSION:-latest}
    build:
      <<: *build_settings
      dockerfile: compose/dockerfiles/base.Dockerfile
    volumes:
      - &rapids_home "${RAPIDS_HOME:-$PWD}:${RAPIDS_HOME:-$PWD}"
      - &rmm "${RAPIDS_HOME:-$PWD}/rmm:${RAPIDS_HOME:-$PWD}/rmm"
      - &cudf "${RAPIDS_HOME:-$PWD}/cudf:${RAPIDS_HOME:-$PWD}/cudf"
      - &compose "${RAPIDS_HOME:-$PWD}/compose:${RAPIDS_HOME:-$PWD}/compose"
      - &cugraph "${RAPIDS_HOME:-$PWD}/cugraph:${RAPIDS_HOME:-$PWD}/cugraph"
      - &custrings "${RAPIDS_HOME:-$PWD}/custrings:${RAPIDS_HOME:-$PWD}/custrings"

  rapids:
    <<: *service_settings
    image: rapidsai/${RAPIDS_NAMESPACE:-anon}/rapids:${RAPIDS_VERSION:-latest}
    build:
      <<: *build_settings
      dockerfile: compose/dockerfiles/rapids.Dockerfile
    ports:
      - "5678:5678"
    volumes:
      - &ptvsd_logs "${RAPIDS_HOME:-$PWD}/compose/etc/rapids/log:/var/log/ptvsd"
      - *rmm
      - *cudf
      - *compose
      - *cugraph
      - *custrings

  notebooks:
    <<: *service_settings
    image: rapidsai/${RAPIDS_NAMESPACE:-anon}/notebooks:${RAPIDS_VERSION:-latest}
    build:
      <<: *build_settings
      dockerfile: compose/dockerfiles/notebooks.Dockerfile
    ports:
      - "5678:5678"
      - "8888:8888"
    volumes:
      - *ptvsd_logs
      - *rmm
      - *cudf
      - *compose
      - *cugraph
      - *custrings
      - &jupyter "${RAPIDS_HOME:-$PWD}/compose/etc/notebooks/.jupyter:/home/rapids/.jupyter"
      - &notebooks_core "${RAPIDS_HOME:-$PWD}/notebooks/cugraph:/home/rapids/notebooks/core"
      - &notebooks_sandbox "${RAPIDS_HOME:-$PWD}/compose/etc/notebooks/sandbox:/home/rapids/notebooks/sandbox"
      - &notebooks_data "${RAPIDS_HOME:-$PWD}/notebooks-extended/data:/home/rapids/notebooks/data"
      - &notebooks_extended "${RAPIDS_HOME:-$PWD}/notebooks-extended:/home/rapids/notebooks/extended"
