version: "3.6"

x-service-settings: &service_settings
  env_file: .env
  network_mode: host
  build: &build_settings
    context: ..
    args:
      UID: ${_UID:-1000}
      GID: ${_GID:-1000}
      BUILD_TESTS: "OFF"
      PYTHON_VERSION: "3.7"
      GCC_VERSION: "${GCC_VERSION:-5}"
      CXX_VERSION: "${CXX_VERSION:-5}"
      RAPIDS_HOME: "${RAPIDS_HOME:-$PWD}"
      COMPOSE_HOME: "${COMPOSE_HOME:-$PWD/compose}"
      CUDA_VERSION: "${CUDA_VERSION:-10.0}"
      RAPIDS_VERSION: "${RAPIDS_VERSION:-latest}"
      RAPIDS_NAMESPACE: "${RAPIDS_NAMESPACE:-anon}"
      LINUX_VERSION: "${LINUX_VERSION:-ubuntu18.04}"

services:

  rapids:
    <<: *service_settings
    image: rapidsai/${RAPIDS_NAMESPACE:-anon}/rapids:${RAPIDS_VERSION:-latest}
    build:
      <<: *build_settings
      dockerfile: ${COMPOSE_HOME:-$PWD/compose}/dockerfiles/rapids.Dockerfile
    volumes:
      - &rapids_home "${RAPIDS_HOME:-$PWD}:${RAPIDS_HOME:-$PWD}"
      - &rmm "${RAPIDS_HOME:-$PWD}/rmm:${RAPIDS_HOME:-$PWD}/rmm"
      - &cudf "${RAPIDS_HOME:-$PWD}/cudf:${RAPIDS_HOME:-$PWD}/cudf"
      - &cuml "${RAPIDS_HOME:-$PWD}/cuml:${RAPIDS_HOME:-$PWD}/cuml"
      - &compose "${COMPOSE_HOME:-$PWD/compose}:${COMPOSE_HOME:-$PWD/compose}"
      - &cugraph "${RAPIDS_HOME:-$PWD}/cugraph:${RAPIDS_HOME:-$PWD}/cugraph"
      - &ptvsd_logs "${COMPOSE_HOME:-$PWD/compose}/etc/rapids/log:/var/log/ptvsd"
      - &bashrc "${COMPOSE_HOME:-$PWD/compose}/etc/rapids/.bashrc:/home/rapids/.bashrc"
      - "${COMPOSE_HOME:-$PWD/compose}/etc/rapids/.bash_history:/home/rapids/.bash_history"

  notebooks:
    <<: *service_settings
    image: rapidsai/${RAPIDS_NAMESPACE:-anon}/notebooks:${RAPIDS_VERSION:-latest}
    build:
      <<: *build_settings
      dockerfile: ${COMPOSE_HOME:-$PWD/compose}/dockerfiles/notebooks.Dockerfile
    ports:
      - "5678:5678"
      - "8888:8888"
    volumes:
      - *ptvsd_logs
      - *rmm
      - *cudf
      - *cuml
      - *compose
      - *cugraph
      - *bashrc
      - &jupyter "${COMPOSE_HOME:-$PWD/compose}/etc/notebooks/.jupyter:/home/rapids/.jupyter"
      - &notebooks_core "${RAPIDS_HOME:-$PWD}/notebooks/cugraph:/home/rapids/notebooks/core"
      - &notebooks_sandbox "${COMPOSE_HOME:-$PWD/compose}/etc/notebooks/sandbox:/home/rapids/notebooks/sandbox"
      - &notebooks_data "${RAPIDS_HOME:-$PWD}/notebooks-contrib/data:/home/rapids/notebooks/data"
      - &notebooks_extended "${RAPIDS_HOME:-$PWD}/notebooks-contrib:/home/rapids/notebooks/extended"

  apt-cacher-ng:
    restart: always
    image: sameersbn/apt-cacher-ng:3.1-3
    ports:
    - "3142:3142"
    volumes:
    - apt-cache:/var/cache/apt-cacher-ng

volumes:
  apt-cache:
