version: "3.6"

x-service-settings: &service_settings
  env_file: .env
  network_mode: host
  build: &build_settings
    context: ..
    args:
      UID: ${_UID:-1000}
      GID: ${_GID:-1000}
      BUILD_TESTS: "OFF"
      PYTHON_VERSION: "${PYTHON_VERSION:-3.7}"
      GCC_VERSION: "${GCC_VERSION:-7}"
      CXX_VERSION: "${CXX_VERSION:-7}"
      RAPIDS_HOME: "${RAPIDS_HOME:-$PWD}"
      COMPOSE_HOME: "${COMPOSE_HOME:-$PWD/compose}"
      CUDA_VERSION: "${CUDA_VERSION:-10.1}"
      RAPIDS_VERSION: "${RAPIDS_VERSION:-latest}"
      RAPIDS_NAMESPACE: "${RAPIDS_NAMESPACE:-anon}"
      LINUX_VERSION: "${LINUX_VERSION:-ubuntu18.04}"
      PARALLEL_LEVEL: "${PARALLEL_LEVEL:-4}"
      USE_FISH_SHELL: "${USE_FISH_SHELL:-}"

services:

  rapids:
    <<: *service_settings
    image: rapidsai/${RAPIDS_NAMESPACE:-anon}/rapids:cuda-${CUDA_VERSION:-10.1}
    build:
      <<: *build_settings
      dockerfile: ${COMPOSE_HOME:-$PWD/compose}/dockerfiles/rapids.Dockerfile
    tty: true
    environment:
      - TERM=xterm-256color
      - NVIDIA_DRIVER_CAPABILITIES=all
    cap_add:
      - SYS_PTRACE
    volumes:
      - &rmm "${RAPIDS_HOME:-$PWD}/rmm:${RAPIDS_HOME:-$PWD}/rmm"
      - &cudf "${RAPIDS_HOME:-$PWD}/cudf:${RAPIDS_HOME:-$PWD}/cudf"
      - &cuml "${RAPIDS_HOME:-$PWD}/cuml:${RAPIDS_HOME:-$PWD}/cuml"
      - &raft "${RAPIDS_HOME:-$PWD}/raft:${RAPIDS_HOME:-$PWD}/raft"
      - &compose "${COMPOSE_HOME:-$PWD/compose}:${COMPOSE_HOME:-$PWD/compose}"
      - &cugraph "${RAPIDS_HOME:-$PWD}/cugraph:${RAPIDS_HOME:-$PWD}/cugraph"
      - &cuspatial "${RAPIDS_HOME:-$PWD}/cuspatial:${RAPIDS_HOME:-$PWD}/cuspatial"
      # - &bashrc "${COMPOSE_HOME:-$PWD/compose}/etc/rapids/.bashrc:${RAPIDS_HOME:-$PWD}/.bashrc"
      - &dot_local "${COMPOSE_HOME:-$PWD/compose}/etc/settings/.local:${RAPIDS_HOME:-$PWD}/.local"
      - &dot_config "${COMPOSE_HOME:-$PWD/compose}/etc/settings/.config:${RAPIDS_HOME:-$PWD}/.config"
      - &dot_ipython "${COMPOSE_HOME:-$PWD/compose}/etc/settings/.ipython:${RAPIDS_HOME:-$PWD}/.ipython"
      - &bash_history "${COMPOSE_HOME:-$PWD/compose}/etc/rapids/.bash_history:${RAPIDS_HOME:-$PWD}/.eternal_bash_history"
      - "/etc/localtime:/etc/localtime"
      - "/etc/timezone:/etc/timezone"
    depends_on:
      - apt-cacher-ng

  notebooks:
    <<: *service_settings
    image: rapidsai/${RAPIDS_NAMESPACE:-anon}/notebooks:cuda-${CUDA_VERSION:-10.1}
    build:
      <<: *build_settings
      dockerfile: ${COMPOSE_HOME:-$PWD/compose}/dockerfiles/notebooks.Dockerfile
    tty: true
    environment:
      - TERM=xterm-256color
      - NVIDIA_DRIVER_CAPABILITIES=all
    ports:
      - "5678:5678"
      - "8888:8888"
    volumes:
      - *rmm
      - *cudf
      - *cuml
      - *raft
      - *compose
      - *cugraph
      - *cuspatial
      # - *bashrc
      - *dot_local
      - *dot_config
      - *dot_ipython
      - *bash_history
      - &jupyter "${COMPOSE_HOME:-$PWD/compose}/etc/notebooks/.jupyter:${RAPIDS_HOME:-$PWD}/.jupyter"
      - &notebooks_contrib "${RAPIDS_HOME:-$PWD}/notebooks-contrib:${RAPIDS_HOME:-$PWD}/notebooks/contrib"
      - &notebooks_sandbox "${COMPOSE_HOME:-$PWD/compose}/etc/notebooks/sandbox:${RAPIDS_HOME:-$PWD}/notebooks/sandbox"
      - "/etc/localtime:/etc/localtime"
      - "/etc/timezone:/etc/timezone"
    depends_on:
      - apt-cacher-ng

  apt-cacher-ng:
    restart: always
    image: sameersbn/apt-cacher-ng:3.1-3
    ports:
    - "3142:3142"
    volumes:
    - apt-cache:/var/cache/apt-cacher-ng

volumes:
  apt-cache:
