version: "3.6"

x-service-settings: &service_settings
  env_file: .env
  build: &build_settings
    context: /opt/rapids
    args:
      UID: ${_UID:-1000}
      GID: ${_GID:-1000}
      BUILD_TESTS: "OFF"
      PYTHON_VERSION: "3.7"
      CUDA_VERSION: "${CUDA_VERSION:-10.0}"
      LINUX_VERSION: "${LINUX_VERSION:-ubuntu18.04}"
      RAPIDS_VERSION: "${RAPIDS_VERSION:-latest}"
      RAPIDS_NAMESPACE: "${RAPIDS_NAMESPACE:-anon}"

x-cudf-volumes: &cudf_volumes
  - &cudf_src_io
    ${CUDF_SOURCE}/python/cudf/io:/opt/rapids/cudf/python/cudf/io
  - &cudf_src_comm
    ${CUDF_SOURCE}/python/cudf/comm:/opt/rapids/cudf/python/cudf/comm
  - &cudf_src_tests
    ${CUDF_SOURCE}/python/cudf/tests:/opt/rapids/cudf/python/cudf/tests
  - &cudf_src_utils
    ${CUDF_SOURCE}/python/cudf/utils:/opt/rapids/cudf/python/cudf/utils
  - &cudf_src_reshape
    ${CUDF_SOURCE}/python/cudf/reshape:/opt/rapids/cudf/python/cudf/reshape
  - &cudf_src_groupby
    ${CUDF_SOURCE}/python/cudf/groupby:/opt/rapids/cudf/python/cudf/groupby
  - &cudf_src_dataframe
    ${CUDF_SOURCE}/python/cudf/dataframe:/opt/rapids/cudf/python/cudf/dataframe

x-notebook-volumes: &notebook_volumes
  - *cudf_src_io
  - *cudf_src_comm
  - *cudf_src_tests
  - *cudf_src_utils
  - *cudf_src_reshape
  - *cudf_src_groupby
  - *cudf_src_dataframe
  - &notebooks_cugraph
    ${NOTEBOOKS_SOURCE}/cugraph:/home/rapids/notebooks/cugraph
  - &notebooks_cuml
    ${NOTEBOOKS_SOURCE}/cuml:/home/rapids/notebooks/cuml
  - &notebooks_xgboost
    ${NOTEBOOKS_SOURCE}/xgboost:/home/rapids/notebooks/xgboost
  - &notebooks_tutorials
    ${NOTEBOOKS_SOURCE}/tutorials:/home/rapids/notebooks/tutorials
  - &notebooks_expert
    ${NOTEBOOKS_EXTENDED_SOURCE}/expert:/home/rapids/notebooks/extended/expert
  - &notebooks_advanced
    ${NOTEBOOKS_EXTENDED_SOURCE}/advanced:/home/rapids/notebooks/extended/advanced
  - &notebooks_beginner
    ${NOTEBOOKS_EXTENDED_SOURCE}/beginner:/home/rapids/notebooks/extended/beginner
  - &notebooks_playground
    ${COMPOSE_SOURCE}/etc/notebooks:/home/rapids/notebooks/playground

services:

  rapids:
    <<: *service_settings
    volumes: *cudf_volumes
    image: rapidsai/${RAPIDS_NAMESPACE:-anon}/rapids:${RAPIDS_VERSION:-latest}
    build:
      <<: *build_settings
      dockerfile: /opt/rapids/compose/dockerfiles/runtime/01-rapids.Dockerfile
    ports:
      - "5678:5678"

  notebooks:
    <<: *service_settings
    volumes: *notebook_volumes
    image: rapidsai/${RAPIDS_NAMESPACE:-anon}/notebooks:${RAPIDS_VERSION:-latest}
    build:
      <<: *build_settings
      dockerfile: /opt/rapids/compose/dockerfiles/runtime/02-notebooks.Dockerfile
    ports:
      - "5678:5678"
      - "8888:8888"
